/**
 * Invoices Page
 *
 * Simple invoice list for club managers.
 * Invoices are auto-generated by the billing system when payments are created.
 * No manual invoice creation - just view and filter.
 */
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useToast } from "@/hooks/use-toast";
import {
  BillingDashboard,
  BillingFilters,
  InvoiceList,
} from "../components";
import {
  fetchInvoices,
  fetchBillingSummary,
} from "../actions/billing-actions";
import type {
  Invoice,
  InvoiceFilters,
  BillingSummary,
} from "@/types/billing";

export function BillingManagementPage() {
  const navigate = useNavigate();
  const { toast } = useToast();

  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [summary, setSummary] = useState<BillingSummary | null>(null);
  const [filters, setFilters] = useState<InvoiceFilters>({});
  const [isLoading, setIsLoading] = useState(true);

  // Load initial data
  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filters]);

  const loadData = async () => {
    try {
      setIsLoading(true);
      const [invoicesData, summaryData] = await Promise.all([
        fetchInvoices(filters),
        fetchBillingSummary(filters),
      ]);
      setInvoices(invoicesData);
      setSummary(summaryData);
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : "Failed to load billing data";
      toast({
        title: "Error",
        description: message,
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleViewInvoice = (invoice: Invoice) => {
    navigate(`/app/billing/${invoice.id}`);
  };

  return (
    <div className="container mx-auto py-8 space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold">Invoices</h1>
        <p className="text-muted-foreground mt-1">
          View payment invoices for all members
        </p>
      </div>

      {/* Summary Dashboard */}
      {summary && <BillingDashboard summary={summary} isLoading={isLoading} />}

      {/* Filters */}
      <BillingFilters
        filters={filters}
        onFiltersChange={setFilters}
        seasons={[]}
        showSeasonFilter={false}
      />

      {/* Invoice List */}
      <InvoiceList
        invoices={invoices}
        onView={handleViewInvoice}
        isLoading={isLoading}
      />
    </div>
  );
}
